id: A06A525D2
title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the Supreme
  Tulku of the Fifth Drubwang Dzogchen Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.337828
  last_modified_at: 2022-03-01 06:00:51.337833
