id: A06A525D2
title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth of
  Khandro Tsering Chödrön'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.323293
  last_modified_at: 2022-03-01 06:00:51.323297
