id: A06A525D2
title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
  Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.343648
  last_modified_at: 2022-03-01 06:00:51.343651
