id: A06A525D2
title: Lamenting Prayer to Jamyang Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.325225
  last_modified_at: 2022-03-01 06:00:51.325230
