id: A06A525D2
title: Prayer to Kongtrul Yönten Gyatso
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.336079
  last_modified_at: 2022-03-01 06:00:51.336084
