id: A06A525D2
title: 'Wondrous Light of the Moon: A Prayer for the Swift Appearance of the Supreme
  Tulku of Vajradhara'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.345274
  last_modified_at: 2022-03-01 06:00:51.345277
