id: A06A525D2
title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.330730
  last_modified_at: 2022-03-01 06:00:51.330733
