id: A06A525D2
title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé Palzangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.326742
  last_modified_at: 2022-03-01 06:00:51.326745
