id: A06A525D2
title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:00:51.320663
  last_modified_at: 2022-03-01 06:00:51.320667
